### ISSUE TITLE
Mala implementación de fingirAmor

### ISSUE THREAD

**Issue by rgonzalezt** [victoriaguillosson/TP-1-PDEP#2]
El enunciado dice: 

> fingirAmor elige a otre enamorade por conveniencia (veremos para qué sirve más adelante).

Es decir, que toma un nombre y un auto para reemplezar el enamorado de un auto, por el nombre que le damos.
Como está hecha ahora `fingirAmor` sólo funciona con el auto `rodra` y eso no está bien porque debería poder funcionar con cualquiera.

**Comment by marcebauer** [comment]
Hola Ro,
No encuentro la manera de resolverlo como decís. El campo `trucoDelAuto` está hecho para recibir una función cuyo tipo sea `Auto -> Auto`. Si le agregara un parámetro más a `fingirAmor` (el String ingresado por el usuario), el campo `trucoDelAuto` para `rodra` entraría en conflicto con la firma que le dimos a los trucos.

**Comment by rgonzalezt** [comment]
Hola Marce, entiendo lo que decís pero, ¿de qué le sirve al auto tener como truco `fingirAmor` si no le pasamos el nombre del enamorade? Entonces, lo que viene es asignarle ese truco pero aplicado parcialmente. Mirá:

`fingirAmor :: String -> Auto -> Auto`

Pero si le pasamos el nombre:

`fingirAmor nombre :: Auto -> Auto`

¿Se entiende?

**Comment by marcebauer** [comment]
Ahora sí. Ya está modificado. Gracias Ro.
