### ISSUE TITLE
Seamos expresives

### ISSUE THREAD

**Issue by rgonzalezt** [victoriaguillosson/TP-1-PDEP#3]
Si tenemos la abstracción `String` hecha, no usemos `[Char]`. Corrijan eso.

**Comment by rgonzalezt** [comment]
El caso del nombre de la función `vocalesEnamorade` tampoco es lo suficiente expresivo. Ese nombre me da a entender que se van a devolver las vocales cuando en realidad lo que devuelve es la _cantidad de vocales_.

**Comment by victoriaguillosson** [comment]
listo!
